### ISSUE TITLE
UCS-2 encoded exception

### ISSUE THREAD

**Issue by pich4ya** [allyomalley/p12CrackerGo#1]
```
$ p12CrackerGo "${wordlistz}"  "${p12_file}" 10

Brute forcing...
panic: pkcs12: string contains characters that cannot be encoded in UCS-2

goroutine 2459771 [running]:
main.guess({0xc00011e000, 0x44531f805a077183, 0x1512f43cf411be1d}, {0xc000488c60, 0x3fbcbeeffcf3416e})
        /root/go/pkg/mod/github.com/allyomalley/p12!cracker!go@v0.0.0-20200514174756-602578ceca03/p12Cracker.go:69 +0x12a
main.crack.func1({0xc000488c60, 0x196cec41}, 0x258874)
        /root/go/pkg/mod/github.com/allyomalley/p12!cracker!go@v0.0.0-20200514174756-602578ceca03/p12Cracker.go:90 +0x50
created by main.crack
        /root/go/pkg/mod/github.com/allyomalley/p12!cracker!go@v0.0.0-20200514174756-602578ceca03/p12Cracker.go:89 +0x4e
```

**Comment by rauanbag** [comment]
```
# go run p12Cracker.go GenPass.txt r1.p12 3

Brute forcing...
panic: asn1: syntax error: indefinite length found (not DER)

goroutine 40583 [running]:
main.guess({0xc000116000?, 0x0?, 0x0?}, {0xc00027a710?, 0x0?})
        /home/rauan/brutecerts/p12CrackerGo/p12Cracker.go:69 +0x10c
main.crack.func1({0xc00027a710, 0x6}, 0x9e58)
        /home/rauan/brutecerts/p12CrackerGo/p12Cracker.go:90 +0x4a
created by main.crack in goroutine 1
        /home/rauan/brutecerts/p12CrackerGo/p12Cracker.go:89 +0x58
exit status 2
```

It gives this error when password is found...
